
# SEO settings
title: Bernease Herman
description: "Bernease Herman's personal website"
keywords: "data science, interpretable models, XAI, FATML, AI, ML, artificial intelligence, machine learning"
url: http://www.berneaseherman.com
baseurl: null

google_analytics:
repo: http://github.com/bernease/bernease.github.io
disqus_shortname: ""

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Bernease Herman
  job      : Data Scientist
  thumb    : assets/images/headshot.png
  email    :
  url      : http://www.berneaseherman.com
  github   : http://github.com/bernease
  twitter  : http://twitter.com/bernease
  facebook : http://facebook.com/bernease
  linkedin : http://linkedin.com/in/bernease

# social settings
og_locale: "pt_US"
twitter_card: "summary_large_image"
twitter_site: "@bernease"

gems:
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "git-jekpush"]
